version: '3.7'
services:

  ######################
  # - Database Container
  database:
    #hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    networks:
      - app-network

  ####################
  # - Server Container
  server:
    container_name: archy.dev-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    image: archy-dev-server
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    env_file: ./server/.env
    command: nodemon server.js
    networks:
      - app-network

  ####################
  # - Client Container
  client:
    container_name: archy.dev-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    image: archy-dev-client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/app/
      - /usr/app/node_modules
    command: npm run start
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local